{
  "version": 2,
  "dgSpecHash": "i11k3LS5QmsmRGGF++B7/Ifc+PcjjjDy0bVKs/xfTus7no+YnD2grjVFYqq/yzaGbbcofjJuBCNbI05gJX2wbw==",
  "success": true,
  "projectFilePath": "C:\\Users\\bruno\\Desktop\\GitHubCDC\\livroprogramacaoparainiciantes\\Capítulo 10 - Tratamentos de erros com exceções Try Catch e Finally\\Desafios\\1\\1.csproj",
  "expectedPackageFiles": [],
  "logs": []
}